/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;
import java.sql.*;
import java.io.FileOutputStream;
import java.util.Date;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
/**
 *
 * @author eater48
 */
public class grSup {
    public static final String JD = "org.apache.derby.jdbc.EmbeddedDriver";
    public static final String DB = "jdbc:derby://localhost:1527/Q2P;create=true";
    
    static Connection con;
    static Statement stm;
    static ResultSet rs;
    static String file = "test.pdf";
    
    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.NORMAL, BaseColor.RED);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
            Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);
    
    private static void addMetaData(Document document) {
        document.addTitle("PDF Report");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("Rajib Firdaus");
        document.addCreator("Rajib Firdaus");
    }
    private static void addTitlePage(Document document)
            throws DocumentException {
        Paragraph preface = new Paragraph();
        // We add one empty line
        addEmptyLine(preface, 1);
        // Lets write a big header
        preface.add(new Paragraph("Data Name of Aplication/Function", catFont));

        addEmptyLine(preface, 1);
        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph(
                "Report generated by: " + System.getProperty("user.name") + ", " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
                smallBold));
        // now add all this to the document
        document.add(preface);
    }
    private static void addContent(Document document) throws DocumentException {
        Anchor anchor = new Anchor("Table Rak", catFont);
        anchor.setName("Table Rak");
        Paragraph catPart = new Paragraph(anchor);
            
        Paragraph paragraph = new Paragraph();
        addEmptyLine(paragraph, 1);
        
        catPart.add(paragraph);

        // add a table
//        createTable(catPart);
// Number of Colomn
        PdfPTable table = new PdfPTable(2);
//         Create Header of Table 
            PdfPCell hc;
            
            hc = new PdfPCell(new Phrase("ID"));
            hc.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(hc);
            hc = new PdfPCell(new Phrase("Nama"));
            hc.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(hc);
            
        table.setHeaderRows(1);
            try {
            Class.forName(JD);
            con=DriverManager.getConnection(DB);
            stm=con.createStatement();
            
            String q = "SELECT*FROM APP.RAK";
            rs=stm.executeQuery(q);
               // loop to add record to table
            while (rs.next()) {
                table.addCell(" "+rs.getString("id"));
                table.addCell(" "+rs.getString("nama"));
                
            
        }

        catPart.add(table);
        stm.close();con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        // now add all this to the document
        document.add(catPart);
    }
    private static void createTable(Paragraph subCatPart)
            throws BadElementException {
        // Number of Colomn
        PdfPTable table = new PdfPTable(2);
//         Create Header of Table 
            PdfPCell hc;
            
            hc = new PdfPCell(new Phrase("ID"));
            hc.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(hc);
            hc = new PdfPCell(new Phrase("Nama"));
            hc.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(hc);
            
        table.setHeaderRows(1);
            try {
            Class.forName(JD);
            con=DriverManager.getConnection(DB);
            stm=con.createStatement();
            
            String q = "SELECT*FROM APP.RAK";
            rs=stm.executeQuery(q);
               // loop to add record to table
            while (rs.next()) {
                table.addCell(" "+rs.getString("id"));
                table.addCell(" "+rs.getString("nama"));
                
            
        }

        subCatPart.add(table);
        stm.close();con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    
    
    private static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }
    
    public static void print(String file){
        try {
                
            Document document = new Document();
                PdfWriter.getInstance(document, new FileOutputStream(file));
                document.open();
                addMetaData(document);
                addTitlePage(document);
                addContent(document);
                addContent(document);
                addContent(document);
                document.close();
                
            
            } catch (Exception e) {
                e.printStackTrace();
            }
    }
    
}
